development:
  adapter: postgresql
  database: project_flow_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: project_flow_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: project_flow_production
  pool: 5
  timeout: 5000
